### ISSUE TITLE
Next breaking release

### ISSUE THREAD

**Issue by timholy** [timholy/SnoopCompile.jl#382]
If I'm not mistaken, #379 and #381 are breaking changes. Before the next release, I'd propose we:
- [x] restrict to Julia 1.10 and higher (#384)
- [x] eliminate `SnoopCompileBot` (#383)
- [x] eliminate `SnoopPrecompile` (#384)
- [x] eliminate `@snoopc` and `@snoopi` (#384)
- [x] possibly rename `@snoopi_deep` to just `@snoopi` or `@snoop_infer` (#386)
- [x] update documentation (#389)

Other thoughts?

**Comment by aviatesk** [comment]
Thanks for putting together the list. Let's focus on finishing it for now. We might come across additional tasks as we go along.

**Comment by mkitti** [comment]
In https://github.com/timholy/SnoopCompile.jl/pull/379 we eliminated the combat declaration for JET.jl. I'm not sure if that was necessary since you can also keep a compact section as long as you also add the package to extras:
https://pkgdocs.julialang.org/v1/creating-packages/#Weak-dependencies

Also, since we are restricting to Julia 1.10 and above here though, perhaps we can restrict the JET.jl compatibility to tighter bounds that make sense for Julia 1.10?

**Comment by mkitti** [comment]
Regarding release time, releasing this when Julia 1.11 comes out should be an objective. I'm not sure how long we have until then or if we have sufficient time to accomplish our goals above. While I see that we are trying to aggregate breaking changes and this is a good goal, I think that should be secondary to have a working package for a released and stable version of Julia.

**Comment by timholy** [comment]
If needed I think we could get this out by next week. Given the number of [open milestones for Julia 1.11](https://github.com/JuliaLang/julia/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.11) I don't think it will be hard to have this ready in time for 1.11.

**Comment by aviatesk** [comment]
I support releasing version 3.0 as soon as we're ready, regardless of when 1.11 is released.

**Comment by timholy** [comment]
The only really big job now is rewriting the documentation. SnoopCompile 2.x was written when we didn't cache native code, and I suspect that this assumption is pervasive in the documentation.

**Comment by oscardssmith** [comment]
What's the status on this? I was just updating packages and realized that it is not currently possible to have latest versions of both JET and SnoopCompile installed.

**Comment by timholy** [comment]
The status is revealed in the checklist above. The only scary one is "update documentation" because there's a huge amount of documentation, and since precompilation the whole landscape has changed.

**Comment by timholy** [comment]
All done! 3.0.0 is on its way out: https://github.com/JuliaRegistries/General/pull/111692
